### ISSUE TITLE
"curl install" and GLIBC

### ISSUE THREAD

**Issue by vrypan** [longaccess/longaccess-client#1]
I followed the instructions and ran:
curl -s http://download.longaccess.com/install.sh | sh

It installed OK, but when trying to run lacli --help, it fails and shows the following traceback:

```
$ lacli --help
[...]
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found 
(required by /home/[...]/local/lib/lacli/libssl.so.10)
```

My system is:

`Linux [...] 3.2.0-54-generic #82-Ubuntu SMP Tue Sep 10 20:08:42 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vrypan** [comment]
It looks like the OS used has a lower version of glibc installed.

**Comment by ahughes117** [comment]
Yes, and it seems that it is a bit of a pain to upgrade the glibc to 2.17 if you are running Ubuntu Linux 12.04 LTS

**Comment by kouk** [comment]
Seems like the only reason the bundled libssl depends on `GLIBC_2.17` is because of the renaming of [`secure_getenv`](https://sourceware.org/glibc/wiki/Tips_and_Tricks/secure_getenv) in recent glibc versions. If we didn't depend on this symbol we would require only `GLIBC_2.16` and above.

**Comment by iantonis** [comment]
Guys, from what I understand you're targeting for a muti-platform solution even on the command-line client, why don't you use Mono ? It's C# for Linux and the benefit is that your C# code will be immediately available in both Windows and Linux world. Ubuntu I think comes with Mono already bundled-in nowadays, so.. if you use C# you already have the multi-platform problem solved. Also, the missing-libs problem solved. Check mono here : http://www.mono-project.com/Main_Page

**Comment by iantonis** [comment]
Also, you should definitely consider Delphi XE platform: http://www.youtube.com/watch?v=yvYftpp12jg for your mobile apps multi-device eco-system.

**Comment by ckotso** [comment]
Predictably enough, this also happens on Mint 13 (based on Ubuntu 12.04-LTS).

**Comment by vrypan** [comment]
@ckotso, @ahughes117  Can you please try again? We've rebuilt the installer and it's probably fixed now.

**Comment by ckotso** [comment]
I didn't check archive creation et al. yet, but the binary starts just fine!

**Comment by ahughes117** [comment]
The binary works fine, I will check all the functionality later. Thanks and congrats!
