### ISSUE TITLE
Cannot login with a > 37 chars password

### ISSUE THREAD

**Issue by loverdos** [longaccess/longaccess-client#2]
How to reproduce: Use the web-ui to update your password to something having 37 or more chars. Then try to 

```
$ lacli login 
```

using the new password. It will fail.

I have reproduced this a few times with passwords of different content, just to be sure. Let me know how I can help to investigate further.

**Comment by loverdos** [comment]
Should be ">= 37" in the title... (famous off-by-one-error)

**Comment by kouk** [comment]
Thanks for the report. Could you tell me what platform you are running on?

**Comment by loverdos** [comment]
OS: OS X 10.9.1
Python:  2.7.6

I tried with a clean installation of `lacli` via:

```
pip install https://github.com/longaccess/longaccess-client/tarball/master
```

earlier today

**Comment by kouk** [comment]
Right, so this seems to be [a problem with a library we use](https://github.com/dreid/treq/issues/47). I've reported it to the developer and hopefully it will be resolved soon. Until then I've committed a temporary fix.

**Comment by loverdos** [comment]
Tried to upgrade. Running

```
$ python setup.py install
```

from inside source folder ends with an error:

```
error: Could not find required distribution treq==0.2.0fixed
```

I also tried

```
$ pip install --upgrade --allow-all-external --allow-unverified treq https://github.com/longaccess/longaccess-client/tarball/master
```

and fails with error:

```
Downloading/unpacking treq==0.2.0fixed (from lacli==0.2)
  Could not find a version that satisfies the requirement treq==0.2.0fixed (from lacli==0.2) (from versions: 0.1.0, 0.2.0)
  Some insecure and unverifiable files were ignored (use --allow-unverified treq to allow).
Cleaning up...
No distributions matching the version for treq==0.2.0fixed (from lacli==0.2)
```

Any pointers?

**Comment by kouk** [comment]
OK, I suppose you have pip version 1.5 which [now defaults to not installing external packages](https://github.com/pypa/pip/pull/1055) and additionally [disables dependency links by default](https://github.com/pypa/pip/commit/12ee7cc6d9e8916ce297f782672bbb74f45f735d). I was running pip 1.4 so it worked for me. It seems that with pip 1.5 there is no way I can force you to install my unverifiable but fixed version of treq, which is a good thing in general. So if you would like you can test the fix by running:

```
$ pip install --upgrade --process-dependency-links --allow-all-external --allow-unverified treq https://github.com/longaccess/longaccess-client/tarball/master
```

In the meantime I hope the treq developer will merge my pull request.

**Comment by loverdos** [comment]
I reinstalled `lacli` from scratch using the provided

```
$ pip install --upgrade --process-dependency-links --allow-all-external --allow-unverified treq https://github.com/longaccess/longaccess-client/tarball/master
```

The installation finished with no error but the original problem persists.

**Comment by kouk** [comment]
sorry I forgot to add you need to add the "--pre" option in order to get pip to accept pre-release versions (I have versioned my fixed clone of treq `0.2.0fixed`). Still haven't heard anything from the treq dev. Hope we don't have to drop it.

**Comment by loverdos** [comment]
`--pre` did the work

**Comment by kouk** [comment]
Thanks. If you don't mind I will keep this open to remember to follow-up with the underlying issue.

**Comment by loverdos** [comment]
No problem. I closed it to make clear that AFAIC the issue is resolved.
